// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/warehouse.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWarehouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWarehouseRequest) Reset() {
	*x = GetWarehouseRequest{}
	mi := &file_proto_warehouse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWarehouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWarehouseRequest) ProtoMessage() {}

func (x *GetWarehouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWarehouseRequest.ProtoReflect.Descriptor instead.
func (*GetWarehouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{0}
}

func (x *GetWarehouseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WarehouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarehouseResponse) Reset() {
	*x = WarehouseResponse{}
	mi := &file_proto_warehouse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarehouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarehouseResponse) ProtoMessage() {}

func (x *WarehouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_warehouse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarehouseResponse.ProtoReflect.Descriptor instead.
func (*WarehouseResponse) Descriptor() ([]byte, []int) {
	return file_proto_warehouse_proto_rawDescGZIP(), []int{1}
}

func (x *WarehouseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WarehouseResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_warehouse_proto protoreflect.FileDescriptor

const file_proto_warehouse_proto_rawDesc = "" +
	"\n" +
	"\x15proto/warehouse.proto\x12\twarehouse\"%\n" +
	"\x13GetWarehouseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x11WarehouseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2d\n" +
	"\x10WarehouseService\x12P\n" +
	"\x10GetWarehouseByID\x12\x1e.warehouse.GetWarehouseRequest\x1a\x1c.warehouse.WarehouseResponseB)Z'microservice-warehouses/proto;warehouseb\x06proto3"

var (
	file_proto_warehouse_proto_rawDescOnce sync.Once
	file_proto_warehouse_proto_rawDescData []byte
)

func file_proto_warehouse_proto_rawDescGZIP() []byte {
	file_proto_warehouse_proto_rawDescOnce.Do(func() {
		file_proto_warehouse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_warehouse_proto_rawDesc), len(file_proto_warehouse_proto_rawDesc)))
	})
	return file_proto_warehouse_proto_rawDescData
}

var file_proto_warehouse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_warehouse_proto_goTypes = []any{
	(*GetWarehouseRequest)(nil), // 0: warehouse.GetWarehouseRequest
	(*WarehouseResponse)(nil),   // 1: warehouse.WarehouseResponse
}
var file_proto_warehouse_proto_depIdxs = []int32{
	0, // 0: warehouse.WarehouseService.GetWarehouseByID:input_type -> warehouse.GetWarehouseRequest
	1, // 1: warehouse.WarehouseService.GetWarehouseByID:output_type -> warehouse.WarehouseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_warehouse_proto_init() }
func file_proto_warehouse_proto_init() {
	if File_proto_warehouse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_warehouse_proto_rawDesc), len(file_proto_warehouse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_warehouse_proto_goTypes,
		DependencyIndexes: file_proto_warehouse_proto_depIdxs,
		MessageInfos:      file_proto_warehouse_proto_msgTypes,
	}.Build()
	File_proto_warehouse_proto = out.File
	file_proto_warehouse_proto_goTypes = nil
	file_proto_warehouse_proto_depIdxs = nil
}
